### ISSUE TITLE
warning when using web component with JSX

### ISSUE THREAD

**Issue by WickyNilliams** [vitejs/vite-plugin-vue#102]
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

i am attempting to use web components in combination with JSX in a vue sfc. i have configured the vite plugin correctly with `isCustomElement`. however if i attempt to use a web component with JSX, i get the following logged to the console:

> Failed to resolve component: my-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
>  at &lt;JSXComponent&gt;
>  at &lt;App&gt;

an example would be:

```vue
<script lang="tsx" setup>
  import "./my-button.ts"
  
  const JSXComponent = () => <my-button>Hello JSX</my-button>
</script>
<template>
  <JSXComponent />
</template>
```

there is no warning if you use the `h()` function instead:

```vue
<script lang="tsx" setup>
  import "./my-button.ts"
  
  const HComponent = () => h("my-button", null, "Hello VNode")
</script>
<template>
  <HComponent />
</template>
```

the compiled code looks like:

```js
const JSXComponent = () => _createVNode(_resolveComponent("my-button"), null, {
  default: () => [_createTextVNode("JSX")]
});
```

i assume the issue is with `_resolveComponent`.

a workaround seems to be:

```vue
<script lang="tsx" setup>
  import "./my-button.ts"
  
  const Tag = "my-button"
  const JSXComponent = () => <Tag>Hello JSX</Tag>
</script>
<template>
  <JSXComponent />
</template>
```

but this is extremely awkward and would not work well at scale.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zzxncb?file=src%2FApp.vue

### Steps to reproduce

open the reproduction link, and open the browser's dev tools console. you should see the warning logged as described

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.81 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0.1
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
    @vitejs/plugin-vue-jsx: ^3.0.0 => 3.0.0
    vite: ^4.1.0 => 4.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
You need to add `isCustomElement` option to vue-jsx plugin too.
```js
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => tag.includes('-'),
        },
      },
    }),
    vueJsx({ isCustomElement: (tag) => tag.includes('-') }),
  ],
});
```

**Comment by WickyNilliams** [comment]
thanks, i didn't realise. sorry to have bothered you
