### ISSUE TITLE
after build newly uploaded images are not show on production on vite4 and vue 3

### ISSUE THREAD

**Issue by Koki81** [vitejs/vite-plugin-vue#108]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I try by doc. on vite to get dynamic images from DB. On production, if I have an image from a user in the assets folder and I build its shows, but if I upload a new image it does not show and it does not bundle the image in the module

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tch6mk?file=src/App.vue

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz
    Memory: 7.89 GB / 15.96 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.46)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
`new URL(url, import.meta.url)` is only meant to be used with static assets.
https://vitejs.dev/guide/assets.html

If you are serving those images on `/src/assets/o,ages/avatars/${name}.jpg`, I guess you can simply use:
```js
function getImageUrl(name) {
  return `/src/assets/images/avatars/${name}.jpg`;
}
```

**Comment by Koki81** [comment]
I found what was problem, can't store image in front-end framework (client
side). So I store on server in nodejs and serve in client-side through
base64 string. And everything is working.
