### ISSUE TITLE
Hot update failed, I don't know if it's a problem with vite or vue

### ISSUE THREAD

**Issue by ketao4869** [vitejs/vite-plugin-vue#124]
### Describe the bug

The hot update of some components failed, and the modified page can be seen in the network request, but the page is not re-rendered
<img width="851" alt="1" src="https://user-images.githubusercontent.com/54937496/223301929-da61b637-14d1-4880-89ea-7dfc733343f7.png">
<img width="827" alt="2" src="https://user-images.githubusercontent.com/54937496/223301933-654763d1-bb28-449c-a5d8-df0186af9c2e.png">
![bug](https://user-images.githubusercontent.com/54937496/223304353-da2fce6e-a73e-4cdd-9794-4db45c427fef.gif)

### Reproduction

https://github.com/ketao4869/vite-bug

### Steps to reproduce

1. pnpm install pnpm run dev
2. Go to `src\Components\SearchForm\index.vue` and modify this file
3. The browser finds that there is no hot update, but the new page in the network request has been requested

4. Go to `src\Components\input\input.vue`, modify this file, and find normal hot update

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.12 GB / 13.86 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1255.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vue: ^3.2.45 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
I was able to reproduce.
When I remove `unplugin-vue-components/vite` from `vite.config.ts`, it worked.

Closing as I guess there's a bug in that plugin.
