### ISSUE TITLE
`process.env.NODE_ENV` is `production` when the mode is `development`

### ISSUE THREAD

**Issue by zyxkad** [vitejs/vite-plugin-vue#127]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I am doing `vite build --mode development --debug true`
I expect `process.env.NODE_ENV` is `development` or `import.meta.env.DEV` is `true` that I can disable something should only appear when my app online.
But node_env is `production` anyway, and meta.DEV also is false

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bpbndz?file=src%2Fmain.js,dist%2Fassets%2Findex-814f35e9.js&terminal=dev

### Steps to reproduce

add this following line to the `main.js` before `createApp`
```js
console.log('process-env-NODE-ENV:', process.env.NODE_ENV)
console.log('import-meta-env-DEV:', import.meta.env.DEV)
```

do `vite build --mode development --debug true --minify false`

check the `index-xxx.js` in `dist/assets`, we will find these lines:
```js
console.log("process-env-NODE-ENV:", "production");
console.log("import-meta-env-DEV:", false);
```

As we see, the node.ENV isn't correct for vite printed `vite v4.2.0-beta.1 building for development...`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0-beta.0 => 4.1.0-beta.0 
    vite: ^4.2.0-beta.1 => 4.2.0-beta.1
```

### Used Package Manager

npm

### Logs

```log
vite v4.2.0-beta.1 building for development...
✓ 16 modules transformed.
dist/index.html                   0.45 kB
dist/assets/vue-5532db34.svg      0.50 kB
dist/assets/index-28cf1a79.css    1.73 kB │ gzip:  0.75 kB
dist/assets/index-814f35e9.js   156.92 kB │ gzip: 36.64 kB
✓ built in 582ms
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
`NODE_ENV` defaults to `production` when building. Changing the mode won't affect `NODE_ENV`.
If you want to change the `NODE_ENV`, you'll need to add a `.env` file or set it by command (e.g. `NODE_ENV=development npm run build`).
https://vitejs.dev/guide/env-and-mode.html#:~:text=As%20vite%20build%20runs%20a%20production%20build%20by%20default%2C%20you%20can%20also%20change%20this%20and%20run%20a%20development%20build%20by%20using%20a%20different%20mode%20and%20.env%20file%20configuration%3A
