### ISSUE TITLE
source map doesn't work when writing block comment at 1st line in sfc script

### ISSUE THREAD

**Issue by alsotang** [vitejs/vite-plugin-vue#133]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Source map of sfc vue file doesn't work when I write a block comment at 1st line. 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/1147375/226625315-a2aacd31-e523-4a9d-87c8-5b1eed637c5c.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1147375/226626048-1c95162d-5cf3-4937-870f-6ed31aac8430.png">

But line comment works well.
<img width="496" alt="image" src="https://user-images.githubusercontent.com/1147375/226625858-a6c2aac2-359d-4e66-a3d5-3801f136fda3.png">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-na671x?file=src%2FApp.vue&terminal=dev

### Steps to reproduce

1. `npm init vue@latest`
2. `cd vue-project`
3. Open `src/App.vue`, and add a whatever block comment `/** whatever comment */` under `<script setup lang="ts">`
4. `npm run dev`
5. Open Chrome and open the sources panel in the devtools. find `App.vue`
6. You should see an empty file

### System Info

```shell
All deps and Chrome are latest versions.

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 247.78 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/Library/Caches/fnm_multishells/35118_1679406099973/bin/node
    npm: 9.2.0 - ~/Library/Caches/fnm_multishells/35118_1679406099973/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Chrome Canary: 113.0.5665.2
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.1.0
    @vitejs/plugin-vue-jsx: ^3.0.0 => 3.0.1
    vite: ^4.1.4 => 4.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
I can't reproduce. I guess it's fixed.
