### ISSUE TITLE
Vite + Pug: Setting classes in child components is not working

### ISSUE THREAD

**Issue by Brugarolas** [vitejs/vite-plugin-vue#141]
### Describe the bug

I'm not sure if it belongs here.

______________________________

When we use Pug with Vite, and we try to add CSS classes to child components, it just won't work. It won't add any classes. For example:

```vue
InputTextarea.mb-xs-4
```

Component `InputTextarea` won't have CSS class `mb-xs-4`.

If we try to use a different syntax, it won't work either:

```vue
InputBase(
  type="textarea",
  :class="[allowResizeClass, autoResizeClass]",
)
```

You can check everything [on my project](https://github.com/Brugarolas/vuersatile-components). Just clone and run it.

### Reproduction

https://github.com/Brugarolas/vuersatile-components/blob/master/lib/components/form/Checkbox.vue

### System Info

```shell
---
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
I wasn't able to reproduce. When I add the class, the element was updated correctly.

**Comment by Brugarolas** [comment]
Yeah, it was the `inheritAttrs: false` thing, which disables `style` and `class` inheritance in Vue 3 (in Vue 2 it didn't), so I removed it.

I think this can be closed. It does not belong here anyway.
