### ISSUE TITLE
mode 区分环境错误 [ mode distinguishing environment error ]

### ISSUE THREAD

**Issue by hututu-yo** [vitejs/vite-plugin-vue#152]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

mode 区分环境错误 [ mode distinguishing environment error ]

### Reproduction

npm create vite@latest

### Steps to reproduce

![image](https://user-images.githubusercontent.com/83563056/233040830-63b51027-5906-41cb-a5bf-6fc8eb4c5cdd.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 4.10 GB / 15.37 GB
  Binaries:
    Node: 14.19.0 - D:\nvm\nodejs\node.EXE
    Yarn: 1.22.5 - D:\Yarn\bin\yarn.CMD
    npm: 6.14.16 - D:\nvm\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.1.0 
    vite: ^4.1.4 => 4.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
`run-p` 传参数时要加引号 https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md
`"run-p type-check 'build-only -- --mode sit'"`

**Comment by hututu-yo** [comment]
![image](https://user-images.githubusercontent.com/83563056/233324522-829e5e20-9dcf-4693-967f-4f25c4ce8503.png)
还是不可以 [ still not possible ]

**Comment by hututu-yo** [comment]
> `run-p`传参数据时要加引号https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md `"run-p type-check 'build-only -- --mode sit'"`

还是不可以 [ still not possible ]

**Comment by sodatea** [comment]
引号加错地方了

**Comment by hututu-yo** [comment]
> 引号加错地方了

加在你那无法打包
![image](https://user-images.githubusercontent.com/83563056/233339784-f7b68db6-4690-4e1a-914f-570933c78f5c.png)

**Comment by sodatea** [comment]
查了一下，在 Windows 下必须用双引号

https://github.com/mysticatea/npm-run-all/issues/45#issuecomment-226458458
把 `'` 改成 `\"` 吧
