### ISSUE TITLE
vite4.3.1无法获取.env下定的变量

### ISSUE THREAD

**Issue by zhou5631** [vitejs/vite-plugin-vue#153]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Description

.env文件
```
VITE_APP_BUILD_TIME=202304211426
```
main.ts
```
console.log(`%cV${import.meta.env.VITE_APP_BUILD_TIME}`, 'color: #ccc;')
```
结果无法获取

### Suggested solution

--

### Alternative

--

### Additional context

--

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sodatea** [comment]
请提供完整可运行的复现代码。

**Comment by sodatea** [comment]
看到你在 Vite 项目下提的 issue 了。
下次请不要在多个地方开重复的 issue，并且请务必提供复现。
