### ISSUE TITLE
"@vitejs/plugin-vue": "4.2.0": Transform failed

### ISSUE THREAD

**Issue by yanhao98** [vitejs/vite-plugin-vue#159]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/37316281/234454812-d8fc6156-fa81-4520-abc1-25f1a226380b.png">

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/37316281/234454894-2d0677a5-79f0-41b0-a83d-1b4f71077ff4.png">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-7ppwwb?file=src/App.vue

### Steps to reproduce

将 `@vitejs/plugin-vue` 的版本号，在 `4.2.0`和`4.1.0`之间切换。

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: 4.2.0 => 4.2.0 
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1 
    vite: ^4.3.2 => 4.3.2
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SPARON** [comment]
我升级后也遇到相同问题
