### ISSUE TITLE
Vue plugin: custom element props get removed when remounted in production build

### ISSUE THREAD

**Issue by elwinvaneede** [vitejs/vite-plugin-vue#16]
### Describe the bug

I have a custom element `test-component` with a `value` prop defined which I want to use in a Vue template like this: `<test-component value="input A"></test-component>`. Vue sees that it has a `value` prop, so it sets this instead of an attribute. In the dev tools, you can see it didn't set an attribute, but the property directly. This works as expected. However, if it gets unmounted by rendering something else and then gets remounted, the prop will not be set. This only happens in the production build (`npm run build` + `npm run preview`), and not with the dev server (`npm run dev`). 

Initial (show input A):
<img width="907" alt="Screen Shot 2022-08-08 at 19 37 31" src="https://user-images.githubusercontent.com/35340250/183483340-25d490b8-1c00-4306-9f7e-952ee8a7a174.png">

After pressing "toggle" (show input B):
<img width="909" alt="Screen Shot 2022-08-08 at 19 37 48" src="https://user-images.githubusercontent.com/35340250/183483354-c229b15c-b032-4ede-9d14-9c5325aed0a9.png">

After pressing "toggle" again (show input A):
<img width="901" alt="Screen Shot 2022-08-08 at 19 38 10" src="https://user-images.githubusercontent.com/35340250/183483364-51a1a44a-4aa9-40c4-b930-24738c66d983.png">

This is not an issue if the property of the custom element gets reflected back to an attribute. But this is not always the case, for example with props that could change a lot, like `value` or `currentTime`.

It's also not an issue when using a ref as a value for the prop.

I have found a workaround by using a unique `key` for each custom element like this: `<test-component value="input A" :key="input-a"></test-component>`, but this is hard to explain to other devs why this is needed.

I can't reproduce it with the Vue CLI (Webpack) production build, so that's why I think it's a Vite + Vue plugin issue. I can't try to reproduce it on https://sfc.vuejs.org/ since it doesn't support allowing custom elements (as far as I know).

It's reproducible with several web component libraries (like [Shoelace](https://shoelace.style/)), as well as in a simple vanilla web component (see reproduction).

### Reproduction

https://github.com/elwinvaneede/vue3-vite-ce-production-build-issue

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 321.30 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 100.0.1
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.0.0 => 3.0.1
    vite: ^3.0.0 => 3.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by poicooler** [comment]
Running into the same issue. The unique key works, you can also wrap the custom element into a vue component to fix this.

Exemple:
```
<template>
  <custom-element :propA="propA" :propB="propB" />
</template>

<script setup lang="ts">
defineProps<{
  propA: string;
  propB: string;
}>();
</script>
```

**Comment by elwinvaneede** [comment]
I can no longer reproduce this issue when using [vue@3.2.45](https://github.com/vuejs/core/blob/main/CHANGELOG.md#3245-2022-11-11), it has a lot of custom-elements related fixes. So it wasn't a Vite + Vue plugin issue, after all.

**Comment by elwinvaneede** [comment]
@sodatea you can close this issue.
