### ISSUE TITLE
升级@vitejs/plugin-vue@4.2.0之后 ERROR: Unterminated regular expression

### ISSUE THREAD

**Issue by LUDA0831** [vitejs/vite-plugin-vue#160]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

升级@vitejs/plugin-vue@4.2.0之后再setup里直接写jsx会报错,@vitejs/plugin-vue@4.1.0没有问题
![image](https://user-images.githubusercontent.com/45849881/234455578-b7974fda-b406-4151-81a1-cba175c844ae.png)

![image](https://user-images.githubusercontent.com/45849881/234455158-706840ed-3c7a-413e-ac85-c6c34007e7a0.png)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-348fqn?file=src%2FApp.vue,package.json&terminal=dev

### Steps to reproduce

"@vitejs/plugin-vue": "4.2.0" 报错
"@vitejs/plugin-vue": "4.1.0" 没问题

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 296.52 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-vue: ^4.2.0 => 4.2.0 
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1 
    vite: ^4.3.2 => 4.3.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LUDA0831** [comment]
有相同问题
https://github.com/vitejs/vite-plugin-vue/issues/159#issue-1684184693

**Comment by SPARON** [comment]
之前4.1.0版本是没有问题的，但是通过升级依赖库后发现4.2.0出现上述问题，然后退回版本到4.1.0、4.0.0依然会出现上述问题，目前退回到3.2.2版本才能正常运行。
