### ISSUE TITLE
The power for devs to supress or alter vite errors based on plugin usage

### ISSUE THREAD

**Issue by louiss0** [vitejs/vite-plugin-vue#168]
### Description

Right now Vue throws an error based on whether a script or template is inserted into the template. While this is good for basic vue apps this is not good when [Vite PluginVue Nested SFC](https://github.com/HunYan-io/vite-plugin-vue-nested-sfc) is used. If you don't know. Vue Nested SFC allows you to create other SFCs inside of an SFC it even automatically exports all of them. 

I ran into an [issue](https://github.com/HunYan-io/vite-plugin-vue-nested-sfc/issues/4) where vite threw an error for not including a script tag or a template inside of an SFC. I went to the plugin author about this but he said he could not do anything. Now I have to put an empty template or script tag in order to stop the error and it does not even allow me to use script setup at all.   

### Suggested solution

I suggest allowing the user of a Vite plugin a way to intercept Vite errors when writing a plugin. This will allow the user to write plugins that don't interfere with the DX of using a tool. I think there is a way for a plugin to know about the existence of another plugin but there should be a way to intercept errors as well.  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sapphi-red** [comment]
The error is thrown from vue compiler that is added by https://github.com/vuejs/core/pull/6781. The rational of this addition is explained at https://github.com/vuejs/core/issues/6676.

I guess `vite-plugin-vue-nested-sfc` can inject `<template></template>` when there aren't any `<template>` or `<script>`.

Closing as this is not something Vite / plugin-vue does. If you think it needs an option to suppress this error, please create an issue on [vuejs/core](https://github.com/vuejs/core).
