### ISSUE TITLE
When using a generic component and a chunk is named by that, it doesn't work after build

### ISSUE THREAD

**Issue by sapphi-red** [vitejs/vite-plugin-vue#169]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

When using a generic component like below,
```vue
<script setup lang="ts" generic="T extends any">
import { ref } from 'vue';

const count = ref(0);
</script>
```
and a chunk is named by that (e.g. `HelloWorld.vue_vue_type_script_setup_true_generic_T%20extends%20any_lang.ts-90b31d22.js`),
it doesn't work after build.

This is happening because

- the built chunk has `import 'HelloWorld.vue_vue_type_script_setup_true_generic_T%20extends%20any_lang.ts-90b31d22.js'`
  - `HelloWorld.vue_vue_type_script_setup_true_generic_T extends any_lang.ts-90b31d22.js` will be fetched.
- the actual built file is `HelloWorld.vue_vue_type_script_setup_true_generic_T%20extends%20any_lang.ts-90b31d22.js`

The root cause here is that rollup isn't aware of the notation of import specifiers. (I mean browsers and Node handles them as a URL but rollup handles them as a raw string.)
[rollup REPL](https://rollupjs.org/repl/?version=3.21.5&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKGF3YWl0JTIwaW1wb3J0KCcuJTJGZm8lMjUyMG8uanMnKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAnZm9vJyUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJmbyUyNTIwby5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCU3RCU3RA==)
I'm not sure where this should be fixed.

related: https://github.com/vitejs/vite-plugin-vue/issues/19#issuecomment-1471409276

### workaround

A workaround is to set the following function to `build.rollupOptions.output.sanitizeFileName`.
```js
// add % to default
// https://github.com/rollup/rollup/blob/742317579d7ca861047fa8320631c7e061f98c02/src/utils/sanitizeFileName.ts#L1-L13
const INVALID_CHAR_REGEX = /[\u0000-\u001F"#$&*+,:;<=>?[\]^`{|}\u007F%]/g;
const DRIVE_LETTER_REGEX = /^[a-z]:/i;
function sanitizeFileName(name) {
  const match = DRIVE_LETTER_REGEX.exec(name);
  const driveLetter = match ? match[0] : '';

  // A `:` is only allowed as part of a windows drive letter (ex: C:\foo)
  // Otherwise, avoid them because they can refer to NTFS alternate data streams.
  return (
    driveLetter +
    name.slice(driveLetter.length).replace(INVALID_CHAR_REGEX, '_')
  );
}
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4nsrrj?file=vite.config.js

### Steps to reproduce

1. Open stackblitz.
2. See dev is working.
3. Run `npm run build && npm run preview`.
4. See build is not working.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.2.1 
    vite: ^4.3.2 => 4.3.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by so1ve** [comment]
I believe this has been fixed

**Comment by sapphi-red** [comment]
Thanks, it seems this is fixed by https://github.com/vitejs/vite-plugin-vue/commit/3170af11f2b6202a9d92fbc6be906026d80b4277.

https://github.com/vuejs/core/issues/8270
