### ISSUE TITLE
Cannot read properties of undefined (reading 'sys')

### ISSUE THREAD

**Issue by JSn1nj4** [vitejs/vite-plugin-vue#181]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I have a type in a .d.ts file, colocated with some components.

I'm exporting an interface and trying to use it in props, but I get an error that seems totally unrelated. The only way around this is to define the interface inside the component I'm trying to use.

This seems to happen specifically with `defineProps<CustomInterface>()`.

On the reproduction below, I didn't switch from NPM. But on my own machine, I was using one of the latest versions of Yarn 1.22.x. The issue happens in both cases.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tvl63j

### Steps to reproduce

1. Create a component
2. Create a .d.ts file like `CustomTypes.d.ts` containing a custom interface and export it:
```typescript
export interface CustomInterface {
  field_one: string;
  field_two: number;
}
```
3. In the component, `import` the interface:
```typescript
import {CustomInterface} from './CustomTypes'
```
4. Pass the interface to `defineProps`:
```typescript
const props = defineProps<CustomInterface>()
```

This is what the error should look like:
![2023-06-02_12-17](https://github.com/vitejs/vite-plugin-vue/assets/5084820/24fcf46c-4c39-4b9e-8725-1f0c513c5af6)

### System Info

```shell
success Install finished in 1.59s


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.2.3 
    vite: ^4.3.2 => 4.3.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JSn1nj4** [comment]
For future reference, after filing a bug report, is it alright if I remove the extra option for either "plugin-vue" or "plugin-vue-jsx" (whichever I don't need for the issue)?

I realize it's not important. Just a little OCD when it comes to "8/9 complete tasks" or something when there's really no 9th. :zipper_mouth_face:

**Comment by sodatea** [comment]
You are trying to use a type import, but `typescript` is not installed as a dependency in the project.

The error message could be improved.
Maybe it's already fixed by https://github.com/vuejs/core/commit/d2c3d8b70b2df6e16f053a7ac58e6b04e7b2078f I'll see if it's so next week after a new canary version is out.

**Comment by JSn1nj4** [comment]
Thanks, that did fix my issue! Apparently it's been a while since I installed the typescript package myself. :sweat_smile:
