### ISSUE TITLE
Vite and plugin-vue 4 generate "process.env" when building as a library.

### ISSUE THREAD

**Issue by crunk1** [vitejs/vite-plugin-vue#190]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I'm trying to upgrade our codebase from vite 2 and plugin-vue 2 to version 4. Our package is being built as a library, but when it is imported, there is a `process is not defined` error. We are not using `process.x` anywhere in our package's source code (aside from our build config files, but that's not an issue). Looking at the compiled code, it looks like vuejs/core itself is being built with `process`.

For example, this line https://github.com/vuejs/core/blob/main/packages/reactivity/src/effect.ts#L51
```typescript
export const MAP_KEY_ITERATE_KEY = Symbol(__DEV__ ? 'Map key iterate' : '')
```
is generating
```javascript
Bo=Symbol(process.env.NODE_ENV!=="production"?"Map key iterate":"")
```
when compiled.

When I remove `build.lib` in our `vite.config.ts`, the compiled code contains no references to `process`, but when I add `build.lib`, it comes back. I've also tried ALL the library formats `['es', 'umd', 'iife', 'cjs']`. They all produce references to `process`.

Our `vite.config.ts`:
```typescript
/// <reference types="vitest" />

import path from 'path'
import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import AutoImport from 'unplugin-auto-import/vite'
import Unocss from 'unocss/vite'
import Banner from 'vite-plugin-banner'

import RemoveDevTools from './plugins/remove-devtools'
import Striptease from './plugins/striptease'

export default defineConfig({
  define: {
    'import.meta.env.BRIDGE_VERSION': JSON.stringify(process.env.npm_package_version),
  },
  build: {
    minify: true,
    lib: {
      name: 'bridge',
      formats: ['iife'],
      fileName: '',
      entry: 'src/main.ts'
    },
    rollupOptions: {
      output: {
        manualChunks: undefined,
        entryFileNames: `bridge.js`,
        assetFileNames: `bridge.[ext]`,
      },
    },
  },

  resolve: {
    alias: {
      '~/': `${path.resolve(__dirname, 'src')}/`,
    },
  },
  plugins: [
    RemoveDevTools(),

    Vue({
      reactivityTransform: true,
    }),

    // https://github.com/antfu/unplugin-auto-import
    AutoImport({
      imports: [
        'vue',
        '@vueuse/core',
      ],
      dts: true,
    }),

    // https://github.com/antfu/vite-plugin-components
    Components({
      dts: true,
    }),

    // https://github.com/antfu/unocss
    // see unocss.config.ts for config
    Unocss(),

    Striptease(),

    Banner(`/* Bridge v${process.env.npm_package_version} XYZ (c) 2020-present. All rights reserved. */`),
  ],

  // https://github.com/vitest-dev/vitest
  test: {
    environment: 'jsdom',
  },
})

```

### Reproduction

This is a private repo and I don't have a minimal repro at this time.

### System Info

```shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 50.12 GB / 62.71 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/sbin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/sbin/npm
    pnpm: 8.6.5 - ~/pnpm/pnpm
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3 
    vite: ^4.3.9 => 4.3.9
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
https://vitejs.dev/guide/build.html#library-mode

> **Environment Variables**
>
> In library mode, all `import.meta.env.*` usage are statically replaced when building for production. However, `process.env.*` usage are not, so that consumers of your library can dynamically change it. If this is undesirable, you can use `define: { 'process.env.NODE_ENV': '"production"' }` for example to statically replace them.

**Comment by crunk1** [comment]
Thank you! I must have missed that part!
