### ISSUE TITLE
build lib, no resolve template customComponent

### ISSUE THREAD

**Issue by qq911512630** [vitejs/vite-plugin-vue#195]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

![image](https://github.com/vitejs/vite-plugin-vue/assets/42533894/87c7da88-02bc-4c29-8b31-544c227494f3)

### Reproduction

-

### System Info

```shell
window
 "vite": "^4.3.9",
 "@vitejs/plugin-vue": "^4.2.3",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qq911512630** [comment]
https://stackblitz.com/edit/vitejs-vite-cypt5s?file=vite.config.js,index.js,views%2Ftest.vue,components%2Fn-text.vue,views%2Findex.js,dist%2Ftest-lib.js&terminal=dev

view **dist/test-lib.js**

![image](https://github.com/vitejs/vite-plugin-vue/assets/42533894/36f42adc-cb55-44c1-a00a-78219b02911d)

**Comment by sodatea** [comment]
Can you describe what the problem is? I don't understand

**Comment by qq911512630** [comment]
选项式API编写的组件，在打包成lib包的时候，template里面的组件没有转化成下面script中已经局部注册的n-text，而是使用的vue语法resolveComponent去找名为'n-text'组件

**Comment by sodatea** [comment]
这个本来就是这么设计的，只不过 script setup 有优化可以跳过这一步。
