### ISSUE TITLE
empty string transform to true 

### ISSUE THREAD

**Issue by wyt930927** [vitejs/vite-plugin-vue#199]
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

🐛 Bug description
 <Field label="" />
_createVNode(Field, { "label": true })

🏞 Desired result
_createVNode(Field, {
"label":""
})

🚑 Other information
Based on the content of the link below, we understand that this issue has been resolved in @vue/babel-plugin-jsx@v1.1.5. We need to upgrade @vue/babel-plugin-jsx version from 1.1.1 to [1.1.5](https://github.com/vuejs/babel-plugin-jsx/commit/a030d15018ca348d0be24d47b6759ea81c668b20)

As we can see, the latest version still references v1.1.1.
https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue-jsx%403.0.1/packages/plugin-vue-jsx/package.json

### Reproduction

https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue-jsx%403.0.1/packages/plugin-vue-jsx/package.json

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 18.72 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 8.6.5 - ~/.nvm/versions/node/v16.20.0/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
`^1.1.1` automatically resolves to the latest 1.x version, which is 1.1.5 at the moment.
Please run `npm update` or `yarn upgrade` or `pnpm update` to update your dependencies in the project.
