### ISSUE TITLE
If i build lib, component can't be correctly resolve in the template

### ISSUE THREAD

**Issue by qq911512630** [vitejs/vite-plugin-vue#203]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Components written using the Vue3 option API, when packaged into a lib package, the components in the template are not converted into corresponding components that have been locally registered in the script, but use the vue syntax resolveComponent to find the corresponding components globally

EXP: 
https://stackblitz.com/edit/vitejs-vite-cypt5s?file=vite.config.js,index.js,views%2Ftest.vue,components%2Fn-text.vue,views%2Findex.js,dist%2Ftest-lib.js&terminal=dev

view dist/test-lib.js

### Reproduction

npm run build

### System Info

```shell
"windows"
 "vue:^3.2.0"
 "vite": "^4.3.9",
 "@vitejs/plugin-vue": "^4.2.3",
```

### Used Package Manager

npm

### Logs

vite build

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
It's expected. It has always worked like this, not related to lib mode.
As long as `resolveComponent` works correctly at runtime, it's not a bug.

And I think there's a misunderstanding here: `resolveComponent` doesn't only look up for global registration, it looks up the locally registered components (`currentInstance.components` during execution) first:
https://github.com/vuejs/core/blob/37a14a5dae9999bbe684c6de400afc63658ffe90/packages/runtime-core/src/helpers/resolveAssets.ts#L103-L108
