### ISSUE TITLE
An option to use esbuild or tsc for compiling .vue file

### ISSUE THREAD

**Issue by ruojianll** [vitejs/vite-plugin-vue#216]
### Description

Now, vite use esbuild to compile typescript code in .vue file. But I need features supported only by vanilla tsc, e.g. stage3 decorators support.

### Suggested solution

Provide an option to config which compiler to use (esbuild or vanilla tsc).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sodatea** [comment]
Esbuild has already supported passing through JavaScript decorators. https://github.com/evanw/esbuild/releases/tag/v0.18.5
So you can post-process the output with TypeScript / Babel / SWC to get the desired result. No need for yet another option.

**Comment by agileago** [comment]
我想使用旧版的装饰器，并且需要 `emitDecoratorMetadata`, 该怎么配置用tsc来转换 vue文件中的脚本部分？

@sodatea

**Comment by sodatea** [comment]
想不到办法。这种场景不建议用 Vite。

**Comment by agileago** [comment]
> 想不到办法。这种场景不建议用 Vite。

真是个悲伤的消息

**Comment by agileago** [comment]
tsx我实现了， 但模版感觉无从下手

https://github.com/agileago/vue3-oop
