### ISSUE TITLE
Slot with v-for breaks hydration

### ISSUE THREAD

**Issue by vitebo** [vitejs/vite-plugin-vue#225]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

When we use a slot with `v-for` and try to access the current item in the slot, the hydration breaks.

To show this bug we have a monorepo with two packages, one is a library and the other is an app that uses the library.
The instructions to reproduce the bug are in the README of the repo.

I no have idea if this is a bug in `@vitejs/plugin-vue` or `nuxt`, if you think this is a bug in `nuxt` please close this issue and I will open a issue in `nuxt`.

### Reproduction

https://github.com/vitebo/nuxt-3-bug-hydration

### Steps to reproduce

1. Run `nvm install` to install the correct version of node
2. Run `npm install` to install the dependencies
3. Run `npm run build -w library` to build the library
4. Run `npm run dev -w app` to start the app

In `packages/app/app.vue` we have two components, one is `ExternalComponent` that is a component from the `library` package and the other is `LocalComponent` that is a copy of `ExternalComponent` but without the `@vitejs/plugin-vue` removed.

We can see that the `ExternalComponent` is not hydrated correctly, but the `LocalComponent` is hydrated correctly.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 117.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.6.5 - /usr/local/bin/pnpm
  Browsers:
    Safari: 16.5.2
```
```


### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
vue.js:1449 [Vue warn]: Hydration text mismatch:
- Client: " "
- Server: " title a" 
  at <ExternalComponent accordionItems= (2) [{…}, {…}] > 
  at <App key=3 > 
  at <NuxtRoot>
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
Let's track this issue in the Vue core repository: https://github.com/vuejs/core/issues/7095
