### ISSUE TITLE
whitespace?: "preserve" | "condense" | undefined

### ISSUE THREAD

**Issue by zhouyu1993** [vitejs/vite-plugin-vue#231]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

**I want to remove all spaces. How it works ?**

`whitespace?: "preserve" | "condense" | undefined`

### In vue-loader, use vue-template-compiler, but in vite, how to do it ?

just like it: 

**PreserveWhitespace**

> The default is true. This means that the compiled rendering function will retain all spaces between HTML tags. If set to false, spaces between labels will be ignored. This can slightly improve performance but may affect the layout of inline elements.

### Reproduction

0

### System Info

```shell
0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          whitespace: 'condense'
        }
      }
    }),
  ]
})
```

https://vuejs.org/api/application.html#app-config-compileroptions-whitespace
