### ISSUE TITLE
No loader is configured for ".vue"

### ISSUE THREAD

**Issue by jaune001** [vitejs/vite-plugin-vue#26]
### Describe the bug

after the import component library, prompt error,

error message：
![image](https://user-images.githubusercontent.com/19927938/144396166-636e53e2-b388-45d7-bbfa-3cff6503a056.png)

@xx/up-ui  is independent research and development components

```
    {
  "name": "vite-vue2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vite",
    "build": "vite build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@xx/up-ui": "^2.1.81",
    "core-js": "^3.6.5",
    "path": "^0.12.7",
    "vite": "^2.3.7",
    "vite-plugin-vue2": "^1.6.2",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^3.0.4",
    "less-loader": "^5.0.0",
    "prettier": "^2.2.1",
    "vue-template-compiler": "^2.6.11"
  }
}

```

### Reproduction

https://github.com/WongYuYe/vite-vue2-demo

vite-vue2-demo  import @xx/up-ui components 

@xx/up-ui is research and development of internal component library

@xx/up-ui  vue: 2.xx

### System Info

```shell
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

node: v14.17.5
npm: 6.14.14
```

### Used Package Manager

npm

### Logs

```shell
npm run serve
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment]
It seems not related to vite-plugin-vue.
try https://github.com/vitejs/vite-plugin-vue2
