### ISSUE TITLE
Vite development mode error when I use string contains '</script>'

### ISSUE THREAD

**Issue by 21dacia** [vitejs/vite-plugin-vue#264]
### Describe the bug

use vite dev，in my .vue file script with setup tag，when a variable which type is string，if it contains '</script>'，then vite will got an error

[vite] Internal server error: Element is missing end tag.

### Reproduction

none

### Steps to reproduce

<template>...</template>

<script lang="ts" setup>
const test: string = "this is the test </script>asdlfklkj"
</script>

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 822.41 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Edge: 106.0.1370.52
    Safari: 17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
This is not supported by vue: https://github.com/vuejs/core/issues/7391
