### ISSUE TITLE
dev模式下，调用esbuild构建时的配置是否可以从vite.config.js同步读取或者支持参数传入？

### ISSUE THREAD

**Issue by jiangkk** [vitejs/vite-plugin-vue#278]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Description

我们的业务有Chrome69的运行场景，在使用Vite的过程中，我们发现生产环境构建出来的代码可以在Chrome69下正常运行，但是dev环境下无法运行。我们尝试使用vite.config.js配置中的esbuild.target来指定执行编译的目标环境，但是通过阅读源码发现这个配置只能修改Vite在编译js,ts等文件才会生效，而.vue文件是通过vite-plugin-vue编译的，并且在调用esbuild的时候是写死了配置（  https://github.com/vitejs/vite-plugin-vue/blob/7d52e6185a749ffedab5980e51aae66ba23b7518/packages/plugin-vue/src/main.ts#L233  ） ，这导致于无法对该编译配置进行修改，是否可以考虑支持在调用esbuild的配置时和vite.config.js里的esbuild配置保持一致或者可以由用户手动传入？

### Suggested solution

希望vite-plugin-vue 在dev环境下调用esbuild配置的时候，可以merge从vite.config.js传入的esbuild配置或者由用户可以手动传入。

### Alternative

目前我们的解决方案是单独再写了一个插件，在vue插件执行完成之后，再调用一次esbuild处理.vue文件，使得可以编译到较低的JavaScript版本，但这样会导致一个文件需要重复编译两次，有一定性能损耗。因此仍希望官方可以支持esbuild配置传入，使得开发者可以自己选择是否需要编译到较低的语法版本，当然这可能会增加编译时间，但可以把这个决定权交给开发者。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aweikalee** [comment]
实际上问题出在：
https://github.com/vitejs/vite-plugin-vue/blob/b43690d09c320fa09428ff5eda213d45dbb34a11/packages/plugin-vue/src/main.ts#L323

当 **.vue** 文件中 `script.lang` 为 `js/ts`（包含为空） 时，会将 `script` 中的代码作为 **.vue** 的内联代码。这使得这部分代码不会被其他处理 `js/ts` 的插件处理。

当 `script.lang` 为 `jsx/tsx` 时，则会以 `import _sfc_main from “xxx.vue?lang.js”` （tsx 时为 `lang.tsx`）形式插入到 **.vue** 文件中。虚拟模块 `xxx.vue?lang.js` 将返回 `script` 中的代码。由于虚拟模块的后缀名是 **.js**，会被当做 **.js** 文件被其他插件处理。

应该废弃内联代码，使其保持一致性：PR #222 。

**Comment by sapphi-red** [comment]
Duplicate of #31
