### ISSUE TITLE
HMR broken with vue + ts + decorators

### ISSUE THREAD

**Issue by Durss** [vitejs/vite-plugin-vue#307]
_First of all, sorry if this has been answered, i've searched litterally for 6h for a solution with no success.
Also I'm not 100% sure the issue comes from vite but I have no deep knowledge of the inner working of this ecosystem :/_

### Describe the bug

I'm trying to get a project on vue + vite + ts + [Vue-facing-decorator](https://github.com/facing-dev/vue-facing-decorator) working with HMR but no matter what I try, HMR does not working.
When I check the websocket connection I get proper messages everytime I CTRI+S a file to notify the page the related module has been updated.
But I get no log on the console as it should and page isn't updated.

Also, if I check the file `http://localhost:8090/src/App.vue` after modifying its source, it is properly updated and on the network tab I see it's loaded.
Styles are loaded and updated correctly.
Basically, things seem to work properly, except for the new script to be executed.

I've had a working project with vite 2.9.12 but after making a clean install of my `node_modules` everything broke _(with this error that I couldn't solve `This experimental syntax requires enabling one of the following parser plugin(s): "decorators", "decorators-legacy"`)_ so I tried to upgrade to latest Vite instead, which gives me a working project but with HMR broken as the last obstacle.

### Reproduction

https://github.com/Durss/vue-vite-hmr-issue

### Steps to reproduce

Install the given repo.
Live reload will not work.

Go to `src/App.vue`, comment the vue component and un comment the one bellow.
Live reload will work.

### System Info

```shell
I get no error or any log.
```

### Used Package Manager

npm

### Logs

<details>
<summary>vite --debug</summary>

```shell
bundled config file loaded in 130.98ms +0ms
using resolved config: {
	plugins: [
	'vite:optimized-deps',
	'vite:watch-package-data',
	'vite:pre-alias',
	'alias',
	'vite:modulepreload-polyfill',
	'vite:resolve',
	'vite:html-inline-proxy',
	'vite:css',
	'vite:esbuild',
	'vite:json',
	'vite:wasm-helper',
	'vite:worker',
	'vite:asset',
	'vite:vue',
	'vite:wasm-fallback',
	'vite:define',
	'vite:css-post',
	'vite:worker-import-meta-url',
	'vite:asset-import-meta-url',
	'vite:dynamic-import-vars',
	'vite:import-glob',
	'vite:client-inject',
	'vite:import-analysis'
	],
	resolve: {
	mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ],
	conditions: [],
	extensions: [
		'.mjs',  '.js',
		'.mts',  '.ts',
		'.jsx',  '.tsx',
		'.json'
	],
	dedupe: [ 'vue' ],
	preserveSymlinks: false,
	alias: [ [Object], [Object], [Object] ]
	},
	server: {
	preTransformRequests: true,
	port: 8090,
	hmr: { port: 8090 },
	sourcemapIgnoreList: [Function: isInNodeModules$1],   
	middlewareMode: false,
	fs: { strict: true, allow: [Array], deny: [Array] }   
	},
	optimizeDeps: {
	disabled: 'build',
	force: undefined,
	esbuildOptions: { preserveSymlinks: false }
	},
	define: { __VUE_OPTIONS_API__: true, __VUE_PROD_DEVTOOLS__: false },
	ssr: {
	target: 'node',
	external: [],
	optimizeDeps: { disabled: true, esbuildOptions: [Object] }
	},
	configFile: 'D:/Projects/vue-vite-ts-template/vite.config.ts',
	configFileDependencies: [ 'D:/Projects/vue-vite-ts-template/vite.config.ts' ],
	inlineConfig: {
	root: undefined,
	base: undefined,
	mode: undefined,
	configFile: undefined,
	logLevel: undefined,
	clearScreen: undefined,
	optimizeDeps: { force: undefined },
	server: { host: undefined }
	},
	root: 'D:/Projects/vue-vite-ts-template',
	base: '/',
	rawBase: '/',
	publicDir: 'D:\\Projects\\Perso\\vue-vite-ts-template\\public',
	cacheDir: 'D:/Projects/vue-vite-ts-template/node_modules/.vite',
	command: 'serve',
	mode: 'development',
	isWorker: false,
	mainConfig: null,
	isProduction: false,
	css: { lightningcss: undefined },
	esbuild: { jsxDev: true },
	build: {
	target: [ 'es2020', 'edge88', 'firefox78', 'chrome87',
'safari14' ],
	cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
	outDir: 'dist',
	assetsDir: 'assets',
	assetsInlineLimit: 4096,
	cssCodeSplit: true,
	sourcemap: false,
	rollupOptions: {},
	minify: 'esbuild',
	terserOptions: {},
	write: true,
	emptyOutDir: null,
	ssrEmitAssets: false,
	reportCompressedSize: true,
	chunkSizeWarningLimit: 500,
	watch: null,
	commonjsOptions: { include: [Array], extensions: [Array] },
	dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
	modulePreload: { polyfill: true },
	cssMinify: true
	},
	preview: {
	port: undefined,
	strictPort: undefined,
	host: undefined,
	https: undefined,
	open: undefined,
	proxy: undefined,
	cors: undefined,
	headers: undefined
	},
	envDir: 'D:/Projects/vue-vite-ts-template',
	env: { BASE_URL: '/', MODE: 'development', DEV: true, PROD: false },
	assetsInclude: [Function: assetsInclude],
	logger: {
	hasWarned: false,
	info: [Function: info],
	warn: [Function: warn],
	warnOnce: [Function: warnOnce],
	error: [Function: error],
	clearScreen: [Function: clearScreen],
	hasErrorLogged: [Function: hasErrorLogged]
	},
	packageCache: Map(1) {
	'fnpd_D:/Projects/vue-vite-ts-template' => {
		dir: 'D:\\Projects\\Perso\\vue-vite-ts-template',
		data: [Object],
		hasSideEffects: [Function: hasSideEffects],
		webResolvedImports: {},
		nodeResolvedImports: {},
		setResolvedCache: [Function: setResolvedCache],
		getResolvedCache: [Function: getResolvedCache]
	},
	set: [Function (anonymous)]
	},
	createResolver: [Function: createResolver],
	worker: { format: 'iife', plugins: '() => plugins', rollupOptions: {} },
	appType: 'spa',
	experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
	getSortedPlugins: [Function: getSortedPlugins],
	getSortedPluginHooks: [Function: getSortedPluginHooks]
} +31ms
```
</details>
<details>
<summary>Logs after doing a modification/CTRL+S on App.ts</summary>

```shell
  vite:hmr [file change] src/App.vue +12s
  vite:hmr [vue:update(template)] D:/Projects/vue-vite-ts-template/src/App.vue +0ms
17:29:15 [vite] hmr update /src/App.vue
  vite:load 0.68ms [fs] /src/App.vue +12s
  vite:cache [memory] /node_modules/.vite/deps/vue-facing-decorator.js?v=4727ca9e +12s
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=4727ca9e +1ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:hmr [self-accepts] src\App.vue +28ms
  vite:import-analysis 2.64ms [4 imports rewritten] src\App.vue +12s
  vite:load 1.66ms [plugin] /src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +9ms
  vite:transform 9.12ms /src/App.vue +12s
  vite:hmr [self-accepts] src\App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +4ms
  vite:import-analysis 0.27ms [0 imports rewritten] src\App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +3ms
  vite:transform 3.21ms /src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +3ms
  vite:time 14.25ms /src/App.vue +12s
  ```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
It seems you need to wrap it with `toNative` (https://github.com/facing-dev/vue-facing-decorator/issues/65#issuecomment-1960895675).
