### ISSUE TITLE
Install error, cannot install @vitejs/plugin-vue-jsx@3.1.0

### ISSUE THREAD

**Issue by lk101** [vitejs/vite-plugin-vue#311]
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Prompt in shell is below:

 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @babel/helper-create-class-features-plugin@^7.23.6

This error happened while installing the dependencies of @vitejs/plugin-vue-jsx@3.1.0
 at @babel/plugin-transform-typescript@7.23.6

The latest release of @babel/helper-create-class-features-plugin is "7.23.5".

Other releases are:
  * next: 8.0.0-alpha.4
  * esm: 7.21.4-esm.4

If you need the full list of all 86 published versions run "$ pnpm view @babel/helper-create-class-features-plugin versions".

### Reproduction

none.url

### Steps to reproduce

```powershell
pnpm install @vitejs/plugin-vue-jsx
```

### System Info

```shell
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @babel/helper-create-class-features-plugin@^7.23.6

This error happened while installing the dependencies of @vitejs/plugin-vue-jsx@3.1.0
 at @babel/plugin-transform-typescript@7.23.6

The latest release of @babel/helper-create-class-features-plugin is "7.23.5".

Other releases are:
  * next: 8.0.0-alpha.4
  * esm: 7.21.4-esm.4

If you need the full list of all 86 published versions run "$ pnpm view @babel/helper-create-class-features-plugin versions".
```

### Used Package Manager

pnpm

### Logs

 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @babel/helper-create-class-features-plugin@^7.23.6

This error happened while installing the dependencies of @vitejs/plugin-vue-jsx@3.1.0
 at @babel/plugin-transform-typescript@7.23.6

The latest release of @babel/helper-create-class-features-plugin is "7.23.5".

Other releases are:
  * next: 8.0.0-alpha.4
  * esm: 7.21.4-esm.4

If you need the full list of all 86 published versions run "$ pnpm view @babel/helper-create-class-features-plugin versions".

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Cannot reproduce
```
❯ pnpm install @vitejs/plugin-vue-jsx
Packages: +92
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 125, reused 89, downloaded 3, added 92, done

dependencies:
+ @vitejs/plugin-vue-jsx 3.1.0

Done in 7.3s
```

**Comment by lk101** [comment]
按照说明查看的@babel/plugin-transform-typescript版本，latest版确实为7.23.6，直接pnpm v @babel/plugin-transform-typescript通过tarball的url也能够将该版本下载下来，但是直接使用pnpm i命令安装时就提示错误

BTW，前段时间vue版本更新的时候，也遇到过同样的问题

registry使用的是https://registry.npmmirror.com

**Comment by lk101** [comment]
> Cannot reproduce. Please try to clean your pnpm cache and try again.
> 
> ```
> ❯ pnpm install @vitejs/plugin-vue-jsx
> Packages: +92
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Progress: resolved 125, reused 89, downloaded 3, added 92, done
> 
> dependencies:
> + @vitejs/plugin-vue-jsx 3.1.0
> 
> Done in 7.3s
> ```

OK, I will try again, thanks.

**Comment by lk101** [comment]
> Cannot reproduce. Please try to clean your pnpm cache and try again.
> 
> ```
> ❯ pnpm install @vitejs/plugin-vue-jsx
> Packages: +92
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Progress: resolved 125, reused 89, downloaded 3, added 92, done
> 
> dependencies:
> + @vitejs/plugin-vue-jsx 3.1.0
> 
> Done in 7.3s
> ```

It really works, thanks a lot.
