### ISSUE TITLE
Can't import defineConfig from vite when using node16 moduleResolution in TypeScript

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vitejs/vite-plugin-vue#312]
### Describe the bug

I'm using https://www.npmjs.com/package/@tsconfig/node20
In my CommonJS project.
I also use the latest vite.

I have this file: `vite.config.ts`
```ts
import { defineConfig } from "vite";

export default defineConfig({});
```

(at this point when filling in the issue I gave up and used `moduleResolution: node`, so the rest is just quick notes on what I tried, etc.)

So basically it gives error, saying that `vite` is ESM.

So I rename `vite.config.ts` in `vite.config.mts` and now import works.

But now all my `plugins: [vue(), vuetify(), vueJsx()],` give errors, saying that import is not callable.
```
import vue from "@vitejs/plugin-vue";
import vueJsx from "@vitejs/plugin-vue-jsx";
import vuetify from "vite-plugin-vuetify";
```

I might not use the latest versions of these.

I "solved" this by doing `vue.default(), vuetify.default()`, etc.

But then when actually trying to run vite - it was saying like undefined is not a function or something.

So at the end I gave up and using `moduleResolution: node` for now.

Hope this helps someone searching for issue, sorry I didn't have time to fill it out properly.

### Reproduction

N/A

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yyx990803** [comment]
Cannot reproduce.
