### ISSUE TITLE
vite+vue-router ｂundle artifact exception when including async routes

### ISSUE THREAD

**Issue by rxliuli** [vitejs/vite-plugin-vue#32]
### Describe the bug

When the following router configuration is used normally, the Modal component displays abnormally after vite is built

```ts
createApp(App)
  .use(Antd as any)
  .use(
    createRouter({
      history: createWebHashHistory(),
      routes: [{ path: '/', component: () => import('./views/Hello.vue') }],
    }),
  )
  .mount('#app')
```

![image](https://user-images.githubusercontent.com/24560368/197164476-a34a1b6a-291d-43eb-836d-bd2763102244.png)

But replace it with the following code

```ts
async function startUp() {
  const Hello = () => import('./views/Hello.vue')
  createApp(App)
    .use(Antd as any)
    .use(
      createRouter({
        history: createWebHashHistory(),
        routes: [{ path: '/', component: Hello }],
      }),
    )
    .mount('#app')
}
```

![image](https://user-images.githubusercontent.com/24560368/197164710-217fc308-9f5d-40cd-b934-f13b189fc4fd.png)

Very strange, not sure why this happens, vite/vue-router/ant-design-vue is involved here, but I guess it may be a vite problem, so I put it here

### Reproduction

https://github.com/rxliuli/vite-build-error-demo

### Steps to reproduce

1. git clone https://github.com/rxliuli/vite-build-error-demo.git
2. pnpm i && pnpm build && pnpm preview
3. open browser

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 34.28 GB / 63.87 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.1.2
    vite: ^3.1.0 => 3.1.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
After updating Vite to 4.4.9, it worked. I believe it was a bug in rollup.
Closing as this is already fixed.
