### ISSUE TITLE
Version 5.0.2 of the plugin breaks the Vue migration build in MODE: 2

### ISSUE THREAD

**Issue by Snip3rSVK** [vitejs/vite-plugin-vue#330]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Hi,
I am moving a Vue 2 (Vite) application to the Vue migration build. After investigation, I found that version 5.0.2 breaks the Vue migration build if configured with MODE: 2. Version 5.0.1 works fine.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-1vh64v?file=package.json

### Steps to reproduce

The reproduction repo should work by default.

Change the `@vitejs/plugin-vue` version from 5.0.1 to 5.0.2 and run `npm install && npm run dev` in the terminal. Vite now outputs an `[plugin:vite:vue] Cannot read properties of undefined (reading 'start')` error.

### System Info

```shell
System:
  OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
  Memory: 2.01 GB / 6.70 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 20.9.0 - /usr/local/bin/node
  Yarn: 3.6.0 - /usr/bin/yarn
  npm: 10.1.0 - /usr/local/bin/npm
  pnpm: 8.11.0 - /usr/local/bin/pnpm
  Watchman: 20230222.123454.0 - /usr/local/bin/watchman
Browsers:
  Chrome: 120.0.6099.62
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by irrg** [comment]
Experiencing the same issue. Pinning to 5.0.1 after reading this bug report—thank you for saving my sanity.

**Comment by sodatea** [comment]
I'm still looking into this issue but here's a workaround:
```
    vue({
      template: {
        compilerOptions: {
          compatConfig: {
            MODE: 2,
            COMPILER_NATIVE_TEMPLATE: false,
          },
        },
      },
    })
```
