### ISSUE TITLE
HMR is broken in a very simple case when using JSX syntax

### ISSUE THREAD

**Issue by fz6m** [vitejs/vite-plugin-vue#353]
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Reproduction Steps:

1. open `src/a.tsx`
2. change the first `v.value` to `v`, web page will lose the value
3. change `v` to `v.value`, HMR broken

### Reproduction

https://stackblitz.com/~/github.com/MoeYc/vue-hmr-broken-simple-case

### System Info

```shell
unrelated
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment]
Maybe it should be compiled like this
```diff
export const A = defineComponent({
  render() {
-    return _createVNode("div", null, [v, _createVNode("button", {
+    return _createVNode("div", null, [toDisplayString(v), _createVNode("button", {
      "onClick": () => {
        v.value++;
      }
    }, [_createTextVNode("+1")])]);
  }
});
```
