### ISSUE TITLE
for a vue(^3.4.21) + vuetify(^3.5.11) project, vite plugin is not supporting for latest vuetify(^3.5.11) components. 

### ISSUE THREAD

**Issue by payal3augustghusalikar** [vitejs/vite-plugin-vue#377]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

i need to use v-treeview, but as per vuetify 3 documentation v-treeview requires vuetify (v3.5.9). so upgraded vuetify version with (v3.5.9) or higher. But it does not loaded treeview component on UI.

### Reproduction

https://github.com/payal3augustghusalikar/vue3-vite-vuetify3

### System Info

```shell
64-bit windows
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sodatea** [comment]
> Labs components require a manual import and installation of the component.

```js
import { VTreeview } from 'vuetify/labs/VTreeview'

export default createVuetify({
  components: {
    VTreeview,
  },
})
```

https://vuetifyjs.com/en/components/treeview/#installation
