### ISSUE TITLE
Vue3 + Vite + Okta Vue, Redirecting path is going wrong in Dev Environment.

### ISSUE THREAD

**Issue by PavankalyanPayyavula** [vitejs/vite-plugin-vue#392]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Hi,

I am working on developing an new application using Vue3 + Vite + Okta Vue and Codebuild.

After configuring everything. When I am running npm start I am able to open application in my local machine - Okta is generating Access Token.
But the problem is when I am deploy the app in dev codebuild then It is not generating Access Token. Even In the local storage access token is getting stored. Attaching respective screenshots for better understanding.
![Screenshot 2024-03-18 at 9 43 45 AM](https://github.com/vitejs/vite-plugin-vue/assets/68322420/0d3905cd-94c9-4b95-a705-521cf8111a3a)

In the network tab, Auth url is redirecting in a loop continues. Here is screenshot.
![Screenshot 2024-03-18 at 11 22 19 AM](https://github.com/vitejs/vite-plugin-vue/assets/68322420/7ddcc9d5-3d36-4cf6-acda-f3d834ad9291)

I tried to console the Auth response. Here is the screenshot of it. You can see the version as well.
![Screenshot 2024-03-18 at 9 47 46 AM](https://github.com/vitejs/vite-plugin-vue/assets/68322420/e73c3217-3cfb-4dc7-bd7b-59481ab68b44)

Hi @yyx990803,
To understand clearly the issue please kindly check this discussion # https://github.com/okta/okta-vue/issues/142
According to them their is some issue with the hosting architecture. 
I have added my vite.config.js file and package.json file information in the issue above.

Note: Redirecting is working fine in Local Environment but It is not working in Dev Environment, Please check the above ticket conversation to understand it. 

### Reproduction

I am not giving any Reproduction since this is not my personal project.

### System Info

```shell
I am using Mac OS,
Node version 20.9.0
Vite 5.2.7
Vue 3.4.21
For all the remaining version details please check the package.json file in the issue that I have raised with Okta Vue #https://github.com/okta/okta-vue/issues/142
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PavankalyanPayyavula** [comment]
@yyx990803 any help on this. I understood that Vite rollup is not able to import Okta Auth library @okta/okta-auth-js after the build. It is working fine when I try to run application in local.

**Comment by patak-dev** [comment]
This doesn't seems to be related to vite-plugin-vue, and there is no minimal reproduction. If you manage to get a minimal reproduction showing an issue in Vite, please share it there. If not, create a Discussion.

**Comment by PavankalyanPayyavula** [comment]
Hi @patak-dev,
Please have look that this issue https://github.com/vitejs/vite/issues/1315.
My issue actually related the above issue. I have followed the solution suggested by Evan. But it is not working.

I understood that this is not related to vite-plugin-vue. But I guess this is related to Vite. Since this is related to authentication library. I cannot manage to get a minimal reproduction showing an issue.
