### ISSUE TITLE
使用vue插槽 热更新失效

### ISSUE THREAD

**Issue by lizhi1255** [vitejs/vite-plugin-vue#4]
### Describe the bug

在element-plus table组件中使用插槽 热更新失效 需要重新刷新页面

### Reproduction

https://github.com/lizhi1255/vite-slot-hot-update-issue

### System Info

```shell
windows,vite,chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by daiyuelin** [comment]
hello，我也遇到了，你有没有解决呢"vite": "^4.0.4",  "vue": "^3.2.25","element-plus": "^2.2.28",

**Comment by sapphi-red** [comment]
Closing as this worked after updating Vue to 3.3.0-beta.1.
I guess https://github.com/vuejs/core/commit/94fa67a4f73b3646c8c1e29512a71b17bd56efc3 fixed this.
