### ISSUE TITLE
update @vue/babel-plugin-jsx to 1.2.2

### ISSUE THREAD

**Issue by DaleMckeown** [vitejs/vite-plugin-vue#408]
### Related plugins

- [x] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [x] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

getting `defineComponent` errors, turns out the dependency for `@vue/babel-plugin-jsx` needs to be pinned to 1.2.2. - https://github.com/vuejs/core/issues/10549.

### Reproduction

https://no.repro.required.

### System Info

```shell
superfluous.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DaleMckeown** [comment]
Fixed in https://github.com/vitejs/vite-plugin-vue/pull/409

**Comment by sxzz** [comment]
Fixed via #371
