### ISSUE TITLE
vite+scss+vant rootValue not match file

### ISSUE THREAD

**Issue by ixqbar** [vitejs/vite-plugin-vue#441]
```
module.exports = {
    plugins: {
        'postcss-pxtorem': {
            rootValue({ file }) {
				console.log(file, file.includes('node_modules/vant'))
                return file.includes('node_modules/vant') ? 37.5 : 75;
            },
            propList: ['*'],
        },
    },
}
```

<img width="1417" alt="image" src="https://github.com/user-attachments/assets/0d838b0c-fed7-466d-9bcc-87c019ec0d0b">

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/83df39a9-3b6f-4037-bfa9-befa62ce9a32">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c461d9b5-ed6c-4e69-b19e-d8abc6b483d0">

<img width="590" alt="image" src="https://github.com/user-attachments/assets/463750f5-fff4-4852-aaf4-4df15f0ccde2">

<img width="261" alt="image" src="https://github.com/user-attachments/assets/85649b18-1379-4064-80ae-9dacd9d08d46">

<img width="1811" alt="image" src="https://github.com/user-attachments/assets/6a902750-a174-459b-905d-5f2e4362539d">

* https://github.com/cuth/postcss-pxtorem/issues/110

不确定到底是vite, postcss-pxtorem, 或者是sass-embedded 谁的问题

### System Info

```shell
"vant": "^4.9.5",
"vue": "^3.5.4",


"devDependencies": {
    "@vant/auto-import-resolver": "^1.2.1",
    "@vitejs/plugin-vue": "^5.1.3",
    "autoprefixer": "^10.4.20",
    "postcss-pxtorem": "^6.1.0",
    "sass-embedded": "^1.78.0",
    "unplugin-auto-import": "^0.18.2",
    "unplugin-vue-components": "^0.27.4",
    "vite": "^5.4.4",
    "vite-plugin-compression": "^0.5.1"
  }
```

**Comment by zhaojjiang** [comment]
I think it is bug belongs to postcss-pxtorem, downgrade postcss-pxtorem@v5.x to solve this
