### ISSUE TITLE
the html tag style content in markdown cause error 'Element is missing end tag'

### ISSUE THREAD

**Issue by wbxl2000** [vitejs/vite-plugin-vue#455]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

when I add html tag style content in markdown, the plugin:vite:vue will be error

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/fb76a527-0a72-4182-8b63-36a88969d330">

### Reproduction

https://stackblitz.com/edit/vite-nk7jtp?file=docs%2Findex.md

### Steps to reproduce

just in the index.md

### System Info

```shell
no need.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment]
Thank you for reporting this issue. It appears to be related to VitePress, specifically when adding HTML tag styles in Markdown. Please report this issue in the VitePress repository so that the relevant maintainers can address and fix it. Thank you!
