### ISSUE TITLE
vite+vue3+ts项目中，.vue文件内的TS不报错!

### ISSUE THREAD

**Issue by bestime** [vitejs/vite-plugin-vue#467]
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

有这么一段代码，编译不会报错，奇葩的是，运行时浏览器不报错，必须要try catch才行。
```vue
// 这个数据可能从一个未知的地方来（来源不重要）
const a:any = {}
console.log(a.b.c.d.e.f.g)
```

然而这个项目也许是别人的，又或许数据来源变了，导致数据结构发生了变化，项目中又有多处这种潜在问题，又无法一一排查，如何能让这个代码在浏览器中直接抛错（试了js、和`非vue文件引用的TS浏览器会抛错`）而且本来也应该抛错

### Reproduction

无

### Steps to reproduce

无

### System Info

```shell
普通浏览器
```

### Used Package Manager

npm

### Logs

npm run dev

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment]
只有一个代码片段，我们是没办法排查问题的。请提供完整的复现 demo。
