### ISSUE TITLE
Hot-module reload doesn't work for :deep(...) CSS selectors

### ISSUE THREAD

**Issue by mspiderv** [vitejs/vite-plugin-vue#54]
### Describe the bug

Im in .vue file. I have some CSS inside my <style scoped>. When I change the CSS, HMR just works fine. But when I use some :deep() selector, it doesn't work (meaning I need to press F5 manually). Seems like Vite is just "watching" changes for regular CSS properties and not for deep.

Example code:

<style lang="scss" scoped>
.table:deep(tbody) {
   font-size: 20px;
}
</style>

### Reproduction

https://stackblitz.com/edit/vitejs-vite-5axdbp?file=src/components/MainComponent.vue

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 12.78 GB / 31.30 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.21.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
I think your reproduction is incorrect.
```css
.some-class:deep(h2)
```
will be transformed to
```css
.some-class[data-v-hash] h2
```
([spec](https://vuejs.org/api/sfc-css-features.html#scoped-css)).
This means `SomeComponent.vue` needs to be like
```vue
<template>
  <div>
    <h2>This is H2 inside SomeComponent.vue</h2>
  </div>
</template>
```
(`h2` should not be the top level element).

After fixing that, I was not able to reproduce it. HMR worked for me.
