### ISSUE TITLE
Replace babel with swc

### ISSUE THREAD

**Issue by mariusa** [vitejs/vite-plugin-vue#59]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Description

Since Vite 4 prefers SWC https://swc.rs/ instead of Babel, how about replacing it for this plugin too? (instead of having a separate plugin with SWC)

### Suggested solution

Replace babel with swc in next major version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sodatea** [comment]
> Since Vite 4 prefers SWC [swc.rs](https://swc.rs/) instead of Babel

It's not true. Babel & SWC have different tradeoffs.

**Comment by patak-dev** [comment]
plugin-vue also doesn't depend on Babel.

**Comment by mariusa** [comment]
> It's not true. Babel & SWC have different tradeoffs.

Thanks for clarification.

> plugin-vue also doesn't depend on Babel

I see these:
https://github.com/vitejs/vite-plugin-vue/blob/f8fb8f6e103ea54b2fbd6f7f7412392098357e5b/package.json#L34
https://github.com/vitejs/vite-plugin-vue/blob/f8fb8f6e103ea54b2fbd6f7f7412392098357e5b/package.json#L37
