### ISSUE TITLE
template  src reference not supported

### ISSUE THREAD

**Issue by StarHosea** [vitejs/vite-plugin-vue#6]
### Describe the bug

A.vue
```vue
<template src="./B.vue">
</template>
<script>
export default {
  
}
</script>
```
B.vue
```
<template>
   <div>This is real template </div>
</template>
```

When Vite build the A.vue in library mod , A Component's render compile result like this
```
function render(_ctx, _cache, $props, $setup, $data, $options) {
  return openBlock(), createElementBlock("template", null, _hoisted_2);
}

```
That will create a template tag in html. By the way, vue-cli  service build works properly

### Reproduction

the repo is 
`https://github.com/StarHosea/vite-template-build-issue.git`

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.43 GB / 15.85 GB
  Binaries:
    Node: 12.18.4 - E:\DevEnv\nodejs\node.EXE
    Yarn: 1.17.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - E:\DevEnv\nodejs\npm.CMD
  Browsers:
    Chrome: 93.0.4577.82
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.31)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
Closing as this isn't expected to work.
https://github.com/vuejs/core/discussions/6929
