### ISSUE TITLE
热更新失效

### ISSUE THREAD

**Issue by ningbnii** [vitejs/vite-plugin-vue#7]
### Describe the bug

在index.vue中import testClass，这时候修改testClass，可以输出console。但是修改index.vue后，再次修改testClass，就不会输出console了

### Reproduction

https://github.com/ningbnii/vite2_vue3_hmr_test

### System Info

```shell
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 3.44 GB / 15.95 GB
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.2145
  npmPackages:
    @vitejs/plugin-vue: ^2.0.1 => 2.0.1
    vite: ^2.7.10 => 2.7.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by enjoy-wind** [comment]
我本地Mac ,js始终无法更新

**Comment by wangjieBABA** [comment]
当我引入一些自定义组件的时候，页面会报出警告，提示我无法识别这个自定义组件，从而无法在页面显示。重启之后就显示正常！

**Comment by feiyayshx** [comment]
遇到同样问题，父组件引入新创建的子组件，热更新编译报错，提示不认识子组件；js文件添加变量引入到父组件也会报错，每次都要重新启动项目，vite启动虽然快，但是热更新问题有待优化！

**Comment by michellesad** [comment]
> 遇到同样问题，父组件引入新创建的子组件，热更新编译报错，提示不认识子组件；js文件添加变量引入到父组件也会报错，每次都要重新启动项目。@vitejs/plugin-vue版本3.1.0

有解决么

**Comment by Gxmg** [comment]
没有办法解决吗？

**Comment by little-buddy** [comment]
快2年了，也没有解决呀，vite的hmr限制写法太多了 😂

**Comment by YellRes** [comment]
@vitejs/plugin-vue 有这段[代码](https://github.com/vitejs/vite-plugin-vue/blob/1963dcf64e89a4955fadc9817168de17aa34501f/packages/plugin-vue/src/main.ts#L152)
```javascript
// check if the template is the only thing that changed
if (prevDescriptor && isOnlyTemplateChanged(prevDescriptor, descriptor)) {
  output.push(`export const _rerender_only = true`)
}
output.push(
  `import.meta.hot.accept(mod => {`,
  `  if (!mod) return`,
  `  const { default: updated, _rerender_only } = mod`,
  `  if (_rerender_only) {`,
  `    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render)`,
  `  } else {`,
  `    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated)`,
  `  }`,
  `})`,
)
```
中有一个_rerender_only的变量，当@vitejs/plugin-vue发现当前代码非首次构建，而且当前只有template标签中发生变化的时候，就会把_rerender_only 设置为true。

_rerender_only 为true时，热更新会执行 __VUE_HMR_RUNTIME__.rerender(xx) 这个函数并不会重新获取组件中的最新的状态值(例如重新执行setup函数得到最新的值)，而从外面导入的值就在setup函数中。

其中判断是否只有template发生变化的isOnlyTemplateChanged代码如下：
```javacript
export function isOnlyTemplateChanged(
  prev: SFCDescriptor,
  next: SFCDescriptor,
): boolean {
  return (
    !hasScriptChanged(prev, next) &&
    prev.styles.length === next.styles.length &&
    prev.styles.every((s, i) => isEqualBlock(s, next.styles[i])) &&
    prev.customBlocks.length === next.customBlocks.length &&
    prev.customBlocks.every((s, i) => isEqualBlock(s, next.customBlocks[i]))
  )
}
```
当script没有发生变化，styles没有发生变化，customBlock没有发生变化的时候，这边默认认为只有template发生了变化。但是当我们修改了外面引入的文件时候同样满足了上述情形，导致了插件认为我们只需要rerender，导致没有获取到最新的setup中的值。

**Comment by ys3322** [comment]
![动画](https://github.com/vitejs/vite-plugin-vue/assets/51523212/ca22b136-b776-407b-abf2-158f27122e74)
- 在使用最新版vite提供的vue模板项目中，也存在热更新问题。
- 一旦修改了template中任意代码，就会导致外部引入的js热更新失效。
- 修改script脚本中的任意代码，就可以恢复外部js文件的热更新
- 具体操作可以看我上述动态图片

测试用到的版本如下：
```json
{
  "name": "my-vite-vue-demo",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "sass": "^1.75.0",
    "vite": "^5.2.0"
  }
}
```
** 这是bug还是特性吗？为什么这么长时间没有解决这问题 **
