### ISSUE TITLE
Unreasonable error reported in Nuxt3 `At least one <template> or <script> is required in a single file component.`

### ISSUE THREAD

**Issue by AuroraTea** [vitejs/vite-plugin-vue#84]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I use `@vite/plugin-vue` in `Nuxt3` for the purpose of using $ref syntactic sugar. But I just introduce and complete the configuration of vite in `nuxt.config.ts` and it all results in an error and does not work. And that the reported errors do not correspond to the factual situation.

### Reproduction

https://codesandbox.io/s/nostalgic-water-7s5dfu

### Steps to reproduce

`pnpm dlx nuxi init test`
`cd test`
`pnpm i`
`pnpm i -D @vitejs/plugin-vue`
```
//in nuxt.config.ts
import vue from '@vitejs/plugin-vue'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  vite: {
    plugins: [
      vue({
        reactivityTransform: true, 
      })
    ],
  }
})
```
`pnpm dev`

### System Info

```shell
Windows 10 Pro 22H2
"@vitejs/plugin-vue": "^4.0.0",
pnpm and yarn both appear, see more in https://codesandbox.io/s/nostalgic-water-7s5dfu
```

### Used Package Manager

yarn

### Logs

 ERROR  At least one <template> or <script> is required in a single file component.
 
 [vite-node] [plugin:vite:vue] [SyntaxError] /node_modules/.pnpm/nuxt@3.0.0/node_modules/nuxt/dist/app/components/nuxt-root.vue
 
 It seems to be a vite error so submit the issue here instead of to nuxt3, and at the same time the content of this error description is completely inconsistent with the actual situation.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AuroraTea** [comment]
for nuxt, we should use
```
export default defineNuxtConfig({
  experimental: {
    reactivityTransform: true
  },
});
```
this issue is for content of  ERROR which print out `At least one or <script> is required in a single file component.`

**Comment by sapphi-red** [comment]
The reason for this error is that plugin-vue inside nuxt converted the vue file to js, and then the added plugin-vue tried to convert the js further.

Because adding multiple plugin-vue makes sense in some setups (e.g. enable `customElement` for a part of the code base), we cannot add a warning or an error.

**Comment by AuroraTea** [comment]
> The reason for this error is that plugin-vue inside nuxt converted the vue file to js, and then the added plugin-vue tried to convert the js further.
> 
> Because adding multiple plugin-vue makes sense in some setups (e.g. enable `customElement` for a part of the code base), we cannot add a warning or an error.

I also considered this possibility and tried it, but the error is the same without adding the additional plugin-vue.

https://codesandbox.io/s/bold-breeze-d77qv4

Sorry I didn't add this test first.

**Comment by sapphi-red** [comment]
That codesandbox link (https://codesandbox.io/s/bold-breeze-d77qv4) does add plugin-vue, no?
Your `nuxt.config.ts`:
```ts
import vue from "@vitejs/plugin-vue";
// https://nuxt.com/docs/guide/directory-structure/nuxt.config
export default defineNuxtConfig({
  telemetry: false,

  vite: {
    plugins: [
      vue({
        reactivityTransform: true
      })
    ]
  }
});
```

**Comment by sapphi-red** [comment]
This is the one I'm saying with "plugin-vue inside nuxt".
https://github.com/nuxt/framework/blob/cd07957c61eebcc314e3bd53f34c81e5093995f5/packages/vite/src/client.ts#L69

So with that nuxt config, it will be like:
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue(), // the one injected by nuxt
    vue({ reactivityTransform: true }) // the one injected by nuxt config
  ]
})
```

In this case,
```vue
<template>
  <div>foo</div>
</template>
```
is transformed to
```js
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/src/App.vue");const _sfc_main = {}
import { openBlock as _openBlock, createElementBlock as _createElementBlock } from "/node_modules/.vite/deps/vue.js?v=ca3d105a"

function _sfc_render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("div", null, "foo"))
}


_sfc_main.__hmrId = "7a7a37b1"
typeof __VUE_HMR_RUNTIME__ !== 'undefined' && __VUE_HMR_RUNTIME__.createRecord(_sfc_main.__hmrId, _sfc_main)
export const _rerender_only = true
import.meta.hot.accept(mod => {
  if (!mod) return
  const { default: updated, _rerender_only } = mod
  if (_rerender_only) {
    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render)
  } else {
    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated)
  }
})
import _export_sfc from '/@id/__x00__plugin-vue:export-helper'
export default /*#__PURE__*/_export_sfc(_sfc_main, [['render',_sfc_render],['__file',"/home/projects/vitejs-vite-xqj5kr/src/App.vue"]])
```
by the first vue plugin and this is pass to the second vue plugin.
This content does not either include `<template>` or `<script>`. So the second vue plugin throws the error.

**Comment by AuroraTea** [comment]
Now I understand exactly what you mean! Thank you for your patience in answering! On a side note, your GitHub Profile is pretty beautiful!
