### ISSUE TITLE
`__vite_ssr_import_meta__.glob is not a function` Error During SSR

### ISSUE THREAD

**Issue by AaronBeaudoin** [vitejs/vite-plugin-vue#96]
### Related plugins

- [x] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

This bug is a very strange one. When using SSR, I cannot use dynamic imports more than once in my Vue SFC if I add `class="whatever"` to the root element. Please see the minimal reproduction, but here is a brief rundown:

1. I'd like to do some ``import(`./dynamicA/${name}.json`)`` and some ``import(`./dynamicB/${name}.json`)`` in my Vue SFC... in other words, I'd like to using dynamic importing multiple times.
2. When I do, the second dynamic import fails if I add `class="whatever"` to the root element of my SFC.
3. This is very surprising outcome, because as a developer I wouldn't expect my `class` attribute and dynamic imports to have anything to do with each other.

### Reproduction

https://github.com/AaronBeaudoin/vite-ssr-issue-vue-sfc-dynamic-import

### Steps to reproduce

Please see the minimal reproduction `README.md` for reproduction steps.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.volta/tools/image/node/16.19.0/bin/node
    npm: 8.19.3 - ~/.volta/tools/image/node/16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.0.4 => 4.0.4
```

### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
/entrypoints/App.vue:8
  console.log("[dynamicB/test.json#message]", (await __vite_ssr_import_0__.default((__vite_ssr_import_meta__.glob("./dynamicB/*.json")), `./dynamicB/${name}.json`)).default.message);
                                                                                                             ^

TypeError: __vite_ssr_import_meta__.glob is not a function
    at asyncWrapper (/entrypoints/App.vue:8:110)
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AaronBeaudoin** [comment]
# Detailed Update

It looks like the root cause of this issue is the output generated for `App.vue` before it is passed to `vite:import-glob` does not correctly quote the "class" attribute, causing it to be interpreted by [Acorn](https://github.com/acornjs/acorn) incorrectly. Here is the relevant snippet from my output:

```js
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${
    _ssrRenderAttrs(_mergeProps({ class: "whatever" }, _attrs))
    //                            ^^^^^
    //                            Here is where I think there should be quotes.
  }>${
    _ssrInterpolate(new Date())
  }</div>`)
}
```

I'm not sure where exactly in the Vite/Rollup pipeline this code is generated. Would someone from the team be willing to jump in here?

**Comment by AaronBeaudoin** [comment]
The Acorn author said the cause of this issue is "not fixable" [on his end](https://github.com/acornjs/acorn/issues/1191#issuecomment-1413454994). That leaves us with a scenario where dynamic import cannot be used more than once (and maybe potentially other issues) if the root element of a component has a `class` attribute. I think this should be resolved by having Vue add quotes around the property name.

**Comment by antfu** [comment]
Thanks for the detailed explanation! v1.0.1 should improve the regex to hand the cases. JS is complex 🤷
